[package]
name = 'satay-ditto-farming'
version = '1.0.0'

[addresses]
satay_ditto_farming = "0xe3eaddfcc4d7436d26fef92ee39685ef176e3513dc736d116129ce055c07afac"

[dependencies.satay]
git = "https://github.com/satay-protocol/satay-aptos"
rev = "main"

[dependencies.ditto-liquidity-mining]
git = "https://github.com/satay-protocol/partner-interfaces"
rev = "master"
subdir = "ditto-lm-interface"